name: Build and Release

on:
  push:
    tags:
      - '*'  # 仅在推送 tag 时执行

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build release binary
        run: cargo build --release

      - name: Rename and move binary
        run: |
          mkdir -p dist
          if [ "${{ runner.os }}" = "Windows" ]; then
            mv target/release/${{ github.event.repository.name }}.exe dist/${{ github.event.repository.name }}-windows.exe
          else
            mv target/release/${{ github.event.repository.name }} dist/${{ github.event.repository.name }}-linux
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
